# Generated by Django 3.1.2 on 2020-11-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirm_password',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(editable=False, max_length=80),
        ),
    ]
