# Generated by Django 3.1.2 on 2020-11-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20201127_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jamb_reg',
        ),
    ]
