# Generated by Django 3.1.2 on 2020-11-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0004_auto_20201124_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatelist',
            name='course',
            field=models.CharField(default='statistics', max_length=50),
            preserve_default=False,
        ),
    ]
