# Generated by Django 3.1.2 on 2020-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0005_aggregatelist_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatelist',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
