# Generated by Django 3.1.2 on 2020-11-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20201107_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
