# Generated by Django 3.1.2 on 2020-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20201107_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
