# Generated by Django 3.1.2 on 2020-11-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20201107_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='aggregateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('jamb', models.PositiveIntegerField()),
                ('post_utme', models.PositiveIntegerField()),
                ('aggregate', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Aggregate Table',
            },
        ),
    ]
