# Generated by Django 3.1.2 on 2020-11-09 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_aggregatelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatelist',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
